# Generated by Django 2.1 on 2019-07-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='document',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
