# Generated by Django 2.1 on 2019-07-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190711_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=15),
        ),
    ]
