# Generated by Django 2.1 on 2019-07-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_document_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='color',
            field=models.CharField(choices=[('util', 'Utilities'), ('cloth', 'Cloths'), ('book', 'Books'), ('toy', 'Toys')], default='green', max_length=15),
        ),
    ]
