# Generated by Django 2.1 on 2019-07-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ditem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='donate/')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
