# Generated by Django 2.1 on 2019-07-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190711_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='password',
            field=models.CharField(default=123, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='email',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='document',
            name='phone',
            field=models.IntegerField(default='123'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
