# Generated by Django 2.1 on 2019-07-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190711_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
