# Generated by Django 2.1 on 2019-07-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190711_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='password',
            new_name='phrase',
        ),
    ]
