# Generated by Django 2.1 on 2019-07-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190712_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='color',
            field=models.CharField(choices=[('equip', 'Equipments'), ('cloth', 'Cloths'), ('book', 'Books'), ('toy', 'Toys')], default='green', max_length=15),
        ),
    ]
