# Generated by Django 2.1 on 2019-07-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190712_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='color',
            new_name='categories',
        ),
    ]
